# Generated by Django 6.0.3 on 2026-03-17 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_sessions', '0001_initial'),
        ('reservations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movie_sessions.session'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('expired', 'Expired')], default='reserved', max_length=10),
        ),
    ]
