# Generated by Django 6.0.3 on 2026-03-18 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_reservation_session_alter_reservation_status'),
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='unique_seat_per_session',
        ),
        migrations.AddField(
            model_name='ticket',
            name='reservation',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ticket', to='reservations.reservation'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='seat_number',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='session',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='status',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
    ]
